version: '3'

dotenv: ['.env', 'secrets/.env']

tasks:
  go:update:
    cmd: go mod tidy
  go:build:
    cmds:
      - |
        GOOS=linux GOARCH=amd64 go build -o main_amd64 main.go
        cp main_amd64 /Users/tstraub/Projects/straubt1.github.com/tf-policy/policies/plugins/tfpolicy-http-plugin_amd64
        # local
        go build -o main_local main.go
        cp main_local /Users/tstraub/Projects/straubt1.github.com/tf-policy/policies/plugins/tfpolicy-http-plugin_darwin