name: Go Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/tfpolicy-http-plugin-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfpolicy-http-plugin-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/tfpolicy-http-plugin-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/tfpolicy-http-plugin-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
